target = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/targets/target" factory="TEXT" variation="lH2"/>"
bst = "detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/bst/bst"        factory="TEXT" variation="java"/>"
cnd = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/cnd/cnd"        factory="TEXT" variation="original"/>"
ctof = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/ctof/ctof"      factory="TEXT" variation="cad"/>"
ctof_cad = "detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/ctof/cad/"      factory="CAD"/>"
htcc = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/htcc/htcc"      factory="TEXT" variation="original"/>"
solenoid = "detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/magnets/solenoid"   factory="TEXT" variation="original"/>"
torus = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/magnets/torus"      factory="TEXT" variation="original"/>"
beamline = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/beamline/beamline" factory="TEXT" variation="FTOn"/>"
ft = "<detector name="/group/clas12/gemc/4a.1.0/experiments/clas12/ft/ft"             factory="TEXT" variation="FTOn"/>"
